# -*- coding: utf-8 -*-
"""segunda-tarefa-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BoRotMAg8THSPBj1mQy8zAS7GITq7m_X
"""

#----------------------------------------------------------------------------------------
#                 Exercícios de Lógica de Programação com PYTHON
#----------------------------------------------------------------------------------------

#Atividade 1: Calculando o Fatorial
#Solicitação: Escreva um programa que peça um número inteiro ao usuário e calcule o fatorial
#desse número.

numero    = int(input("Digite um número inteiro: "))
resultado = 1
contador  = 1

while contador <= numero:
    resultado *= contador
    contador += 1

print('\nO resultado de {}! é: {}'.format(numero, resultado))

#Atividade 2: Conversão de Temperaturas
#Solicitação: Crie um programa que converta uma temperatura dada em Celsius para Fahrenheit
#e Kelvin.
celsius   = int(input("Digite a temperatura em Celsius: "))
farenheit =  (celsius * 9/5) + 32
print("A temperatura informada em Farenheit é : ", farenheit)

#Atividade 3: Cálculo de IMC
#Solicitação: Escreva um programa que peça o peso e a altura de uma pessoa e calcule seu
#Índice de Massa Corporal (IMC)
peso    = int(input("Digite o peso: "))
altura  = float(input("Digite a altura: "))
IMC     = peso / (altura * altura)
print("O IMC é : ", IMC)

#Atividade 4: Verificação de Palíndromo
#Solicitação: Crie um programa que verifique se uma palavra ou frase é um palíndromo
# Solicita ao usuário que digite uma palavra ou frase
entrada = input("Digite uma palavra ou frase: ")

texto = entrada.lower()
texto = texto.replace(" ", "")
texto = texto.replace(",", "")
texto = texto.replace(".", "")
texto = texto.replace("!", "")
texto = texto.replace("?", "")

texto_invertido = texto[::-1]


if texto == texto_invertido:
    print("É um palíndromo!")
else:
    print("Não é palíndromo.")

#Atividade 5: Tabuada
#Solicitação: Escreva um programa que exiba a tabuada de um número fornecido pelo usuário.
numero = int(input("Digite um número: "))
for i in range(1,11):
  print(numero , " X " , i , " = " , (numero * i))

#Atividade 6: Contagem de Vogais
#Solicitação: Crie um programa que peça uma frase ao usuário e conte quantas vogais (a, e, i, o, u) ela contém

frase     = input("Digite uma frase: ")
frase     = frase.lower()
vogais    = "aeiou"
contador_vogais = 0

for letra in frase:
    if letra in vogais:
        contador_vogais += 1
print("Total de vocgais :" , contador_vogais)

#Atividade 7: Média de Notas
#Solicitação: Desenvolva um programa que calcule a média de várias notas inseridas pelo usuário.
#O programa deve parar de pedir notas quando o usuário digitar -1.

soma = 0
qtdNotas = 0
nota = int(input("Digite a nota ou -1 para finalizar"))

while nota != -1:
  soma += nota
  qtdNotas = qtdNotas + 1
  nota = int(input("Digite a nota ou -1 para finalizar"))

media = soma / qtdNotas
print("Média é : ", media)

#Atividade 8: Sequência de Fibonacci
#Solicitação: Escreva um programa que mostre os primeiros n números da sequência de
#Fibonacci, onde n é informado pelo usuário
#
n     = int(input("Digite o número de termos da sequência de Fibonacci : "))

a, b  = 0, 1
contador = 0

if n <= 0:
    print("Digite um número positivo")
elif n == 1:
    print("Sequência de Fibonacci até ", n, "termo: ")
    print(a)
else:
    print("Sequência de Fibonacci:")
    while contador < n:
        print(a)
        a, b = b, a + b
        contador += 1



#Atividade 9: Ordenação de Números
#Solicitação: Crie um programa que leia três números diferentes e os imprima em ordem
#crescente.

numero1 = int(input("Digite o primeiro número: "))
numero2 = int(input("Digite o segundo número: "))
numero3 = int(input("Digite o terceiro número: "))
menor, meio, maior, auxiliar = 0,0,0,0

if(numero1 < numero2 and numero1 < numero3):
  menor = numero1
if(numero2 < numero1 and numero2 < numero3):
  menor = numero2
if(numero3 < numero1 and numero3 < numero2):
  menor = numero3

if(numero1 > numero2 and numero1 > numero3):
  maior = numero1
if(numero2 > numero1 and numero2 > numero3):
  maior = numero2
if(numero3 > numero1 and numero3 > numero2):
  maior = numero3

if(numero1 != menor and  numero1 != maior):
  meio = numero1
if(numero2 != menor and  numero2 != maior):
  meio = numero2
if(numero3 != menor and  numero3 != maior):
  meio = numero3

print("Os números na ordem crescente são : ", menor, meio, maior)

#Atividade 10: Números Pares e Ímpares
#Solicitação: Escreva um programa que peça ao usuário um número inteiro e informe se ele é par ou ímpa
numero = int(input("Digite um número inteiro: "))
if(numero %2 == 0):
  print("É par")
else:
  print("É impar")

#Atividade 11: Cálculo de Área de Círculo
#Solicitação: Desenvolva um programa que calcule a área de um círculo a partir do raio fornecido pelo usuário.
raio = int(input("Digite o valor do raio"))
area = 3.1416 * (raio * raio)
print("Area é :", area)

#Atividade 12: Jogo de Adivinhação
#Solicitação: Crie um jogo onde o programa escolhe um número aleatório entre 1 e 100, e o
#usuário deve adivinhar qual é o número.


    numero_secreto = random.randint(1, 100)
    tentativas = 0
    print("Bem-vindo ao jogo de adivinhação!")
    print("Tente adivinhar o número entre 1 e 100.")

    while True:
        palpite = int(input("Digite seu palpite: "))
        tentativas += 1

        if palpite < numero_secreto:
            print("Muito baixo! Tente novamente.")
        elif palpite > numero_secreto:
            print("Muito alto! Tente novamente.")
        else:
            print(f"Parabéns! Você acertou o número em {tentativas} tentativas.")
            break

#Atividade 13: Soma de Números Pares
#Solicitação: Escreva um programa que calcule a soma de todos os números pares entre 1 e 100

soma = 0
for i in range (1,101):
  if (i % 2 == 0):
    soma+=i
print("Soma dos numeros pares entre 1 e 100 é :", soma)

#Atividade 14: Calculadora Simples
#Solicitação: Crie um programa que funcione como uma calculadora simples, pedindo ao usuário dois números e a operação que deseja realizar.

numero1 = int(input("Digite o primeiro número :"))
numero2 = int(input("Digite o segundo número :"))
operacao = input("Digite a operação + - * / ")
resultado = 0;

if(operacao == "+"):
  resultado = numero1 + numero2
elif(operacao == "-"):
  resultado = numero1 - numero2
elif(operacao == "*"):
  resultado = numero1 * numero2
elif(operacao == "/"):
  resultado = numero1 / numero2
else:
  print("Operacao inválida")


print("Resultado é :", resultado)

#Atividade 15: Soma dos N primeiros Números
#Solicitação: Escreva um programa que peça ao usuário um número n e calcule a soma dos primeiros n números naturais.
n = int(input("Digite um número natural: "))

soma_formula = n * (n + 1) // 2
print(f"Soma dos primeiros {n} números naturais: {soma_formula}")

#Atividade 16: Inversão de String
#Solicitação: Crie um programa que peça uma string ao usuário e a exiba invertida.
#Lógica: O programa precisa pegar a string fornecida pelo usuário e inverter a ordem dos
#caracteres, podendo usar slicing ou um loop para construir a string invertida

string = input("Digite uma string: ")
string_invertida = string[::-1]

print(f"String invertida: {string_invertida}")

#atividade 17: Verificação de Número Perfeito
#Solicitação: Escreva um programa que verifique se um número dado é um número perfeito.
def eh_perfeito(n):

    soma_divisores = 0


    for i in range(1, n):
        if n % i == 0:
            soma_divisores += i


    return soma_divisores == n


numero = int(input("Digite um número: "))


if eh_perfeito(numero):
    print(f"{numero} é um número perfeito.")
else:
    print(f"{numero} não é um número perfeito.")



#Atividade 18: Contagem de Palavras
#Solicitação: Desenvolva um programa que conte quantas palavras há em uma frase fornecida #pelo usuário.
frase     = input("Digite uma frase")
palavras  = frase.split()
numerosDePalavras = len(palavras)
print("Total de palavras : ", numerosDePalavras)

#Atividade 19: Média Ponderada
#Solicitação: Crie um programa que calcule a média ponderada de três notas fornecidas pelo
#usuário, considerando os pesos 2, 3 e 5.

nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))

peso1 = 2
peso2 = 3
peso3 = 5


media_ponderada = (nota1 * peso1 + nota2 * peso2 + nota3 * peso3) / (peso1 + peso2 + peso3)


print(f"A média ponderada das notas é: {media_ponderada:.2f}")

#Solicitação: Escreva um programa que peça ao usuário uma lista de números e, ao final, exiba o
#maior, o menor, e a média dos números inseridos.
numeros = input("Digite uma lista de números separados por espaço: ").split()
numeros = [float(numero) for numero in numeros]

maior_numero = max(numeros)
menor_numero = min(numeros)
media = sum(numeros) / len(numeros)


print(f"O maior número é: {maior_numero}")
print(f"O menor número é: {menor_numero}")
print(f"A média dos números é: {media:.2f}")